plugins {
	id 'java'
	id 'org.springframework.boot' version '3.2.2'
	id 'io.spring.dependency-management' version '1.1.4'
}

group = 'kr.dteng'
version = '1.0.0-SNAPSHOT'

java {
	sourceCompatibility = '17'
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-web'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	
	//thymeleaf 의존성 주입
    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'    
    
    //Thymeleaf Layout Dialect 의존성 주입
    implementation 'nz.net.ultraq.thymeleaf:thymeleaf-layout-dialect:3.0.0'
    
    //메일 발송을 위한 의존성 주입
    implementation 'org.springframework.boot:spring-boot-starter-mail'
    
}

tasks.named('test') {
	useJUnitPlatform()
}